spring.application.name=fitpass

spring.datasource.url=jdbc:mysql://localhost:3306/fitpass_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

supabase.url=https://zqojacsfpjmiiacvxetk.supabase.co/rest/v1
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxb2phY3NmcGptaWlhY3Z4ZXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE0MTgzOTIsImV4cCI6MjEwNjk5NDM5Mn0.mttjzF3eroBsHXJe6KwgDWBJ8pKr_Bzj7nyI-MUJ7bA
server.port=8080